package vk_warehousing.transportAutragsErstellung.gui;


import java.io.File;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import vk_warehousing.transportAutragsErstellung.auftrag.data.Auftrag;
import vk_warehousing.transportAutragsErstellung.auftrag.model.AuftragTableModel;
import vk_warehousing.transportAutragsErstellung.auftragFilter.AlleAuftragFilter;
import vk_warehousing.transportAutragsErstellung.auftragFilter.AuftragByTNrFilter;
import vk_warehousing.transportAutragsErstellung.config.data.Config;
import vk_warehousing.transportAutragsErstellung.config.dlg.ConfigDialog;
import vk_warehousing.transportAutragsErstellung.transport.data.DauerInputVerifier;
import vk_warehousing.transportAutragsErstellung.transport.data.Transport;
import vk_warehousing.transportAutragsErstellung.transport.model.TransportTableModel;

public class TransportAuftragsErstellungGUI extends javax.swing.JFrame {

    private TransportTableModel transportModel;
    private AuftragTableModel auftragModel;
    
    private Transport selectedTransport = null;
    
    public TransportAuftragsErstellungGUI() {
        initComponents();
        //TableModel erzeugen und mit Table verknüpfen
        transportModel = new TransportTableModel();
        tTranporte.setModel(transportModel);
        auftragModel = new AuftragTableModel();
        tAuftraege.setModel(auftragModel);
        //Input Verifer für Dauer
        ftfDauerBisBeladung.setInputVerifier(new DauerInputVerifier());
         //Init Combobox
        initConfig();
    }

    private void initConfig()
    {
        cbTransportNummer.setModel(
                Config.theInstance().
                        getTransportModel());
         
        cbRoutenNummer.setModel(
                Config.theInstance().
                        getRoutenModel());        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfAnzahlAuftraege = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btTHinzufuegen = new javax.swing.JButton();
        cbTransportNummer = new javax.swing.JComboBox();
        cbRoutenNummer = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        ftfDauerBisBeladung = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTranporte = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        tfAuftragsPfad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btLadeAuftraege = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btAHinzufuegen = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lTransportNummer = new javax.swing.JLabel();
        btZeigeAlleAuftraege = new javax.swing.JButton();
        btZeigeAuftraegeFueTnr = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAuftraege = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        miConfig = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transport-Auftrags Erstellung");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Transport-Erstellung"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Transport Nr:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(jLabel3, gridBagConstraints);

        jLabel2.setText("Routen Nr:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(jLabel2, gridBagConstraints);

        tfAnzahlAuftraege.setColumns(20);
        tfAnzahlAuftraege.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(tfAnzahlAuftraege, gridBagConstraints);

        jLabel1.setText("Anzahl Aufträge:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(jLabel1, gridBagConstraints);

        btTHinzufuegen.setText("T Hinzufügen");
        btTHinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnTransportHinzufuegen(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(btTHinzufuegen, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(cbTransportNummer, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(cbRoutenNummer, gridBagConstraints);

        jLabel8.setText("Dauer bis Beladg.:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(jLabel8, gridBagConstraints);

        ftfDauerBisBeladung.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        ftfDauerBisBeladung.setText("00:01");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(ftfDauerBisBeladung, gridBagConstraints);

        jPanel1.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel4.setPreferredSize(new java.awt.Dimension(452, 70));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        tTranporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tTranporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onTransportMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tTranporte);

        jPanel4.add(jScrollPane1);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Auftrags-Zuweisung"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.GridBagLayout());

        tfAuftragsPfad.setColumns(20);
        tfAuftragsPfad.setText("vk_warehousing/auftraege.txt");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel7.add(tfAuftragsPfad, gridBagConstraints);

        jLabel6.setText("Auftrags Pfad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        jPanel7.add(jLabel6, gridBagConstraints);

        btLadeAuftraege.setText("Lade Aufträge");
        btLadeAuftraege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onLadeAuftraege(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel7.add(btLadeAuftraege, gridBagConstraints);

        jPanel2.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        btAHinzufuegen.setText("A Hinzufügen");
        btAHinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAHinzufuegen(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel5.add(btAHinzufuegen, gridBagConstraints);

        jLabel7.setText("TransportNummer:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel5.add(jLabel7, gridBagConstraints);

        lTransportNummer.setText("----");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel5.add(lTransportNummer, gridBagConstraints);

        btZeigeAlleAuftraege.setText("Zeige Alle");
        btZeigeAlleAuftraege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onZeigeAlleAuftraege(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel5.add(btZeigeAlleAuftraege, gridBagConstraints);

        btZeigeAuftraegeFueTnr.setText("Zeige für T Nr");
        btZeigeAuftraegeFueTnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onZeigeAlleAuftraege1(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel5.add(btZeigeAuftraegeFueTnr, gridBagConstraints);

        jPanel2.add(jPanel5, java.awt.BorderLayout.WEST);

        jPanel6.setPreferredSize(new java.awt.Dimension(452, 70));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        tAuftraege.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tAuftraege.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onAuftragMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tAuftraege);

        jPanel6.add(jScrollPane2);

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Extras");

        miConfig.setText("Config");
        miConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onConfig(evt);
            }
        });
        jMenu3.add(miConfig);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onConfig(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onConfig
        try
        {
            ConfigDialog dlg =
                    new ConfigDialog(this,true);
            //Daten auslesen und setzen möglich
            dlg.setVisible(true);
            //Daten auslesen und setzen möglich
            if (dlg.isOkay())
            {
                initConfig();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }
    }//GEN-LAST:event_onConfig

    private void OnTransportHinzufuegen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnTransportHinzufuegen
        try
        {
            //todo Plausi: Anzahl checken
            if (tfAnzahlAuftraege.getText().isEmpty())
            {
                throw new Exception("Anzahl eingeben!");
            }
            int anzahl = new Integer(tfAnzahlAuftraege.getText());
            if (anzahl<=0 || anzahl>=100)
            {
                throw new Exception("Anzahl nur zwischen 1 und 100");
            }
            //Okay => Transport erstellen
            Transport t = new Transport(
                    (String) cbTransportNummer.getSelectedItem(),
                    (String) cbRoutenNummer.getSelectedItem(),
                    anzahl,
                    ftfDauerBisBeladung.getText()
                        );
            transportModel.add(t);
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,
                    e.toString());
        }        
    }//GEN-LAST:event_OnTransportHinzufuegen

    private void onAHinzufuegen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAHinzufuegen
        try
        {
            int row = tAuftraege.getSelectedRow();
            if (row<0)
            {
                throw new Exception ("Selektiere Auftrag!");
            }
            Auftrag a = auftragModel.get(row);
            //todo verbessern mit Ableitung TransportAuftrag klasse
            a.setTransportNummer(selectedTransport.getTransportNummer());
            transportModel.addAuftrag(selectedTransport, a);
            auftragModel.fireTableDataChanged();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }         

    }//GEN-LAST:event_onAHinzufuegen

    private void onTransportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onTransportMouseClicked
        try
        {
            int row = tTranporte.getSelectedRow();
            if (row<0)
            {
                throw new Exception ("Selektiere Transport!");
            }
            selectedTransport = transportModel.get(row);
            
            lTransportNummer.setText(selectedTransport.
                            getTransportNummer());
            //Auftrag-Daten von TransportModel holen
            //und im Table Model setzen
//            auftragModel.setAuftraege(
//                        selectedTransport.getAufraege()
//            );
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }         
    }//GEN-LAST:event_onTransportMouseClicked

    private void onLadeAuftraege(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onLadeAuftraege
        try
        {
            String path ="src/"+tfAuftragsPfad.getText();
            path = path.substring(0,path.lastIndexOf("/"));
            System.out.println("path:"+path);
            File file = new File(path);
            JFileChooser chooser = new JFileChooser(
                    file);
            chooser.setCurrentDirectory(file);
            int answer = chooser.showOpenDialog(this);
            if (answer==JFileChooser.APPROVE_OPTION)
            {
                //todo read from File
                auftragModel.load();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }  
    }//GEN-LAST:event_onLadeAuftraege

    private void onAuftragMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onAuftragMouseClicked
        try
        {
            if (evt.getClickCount()==2)
            {
                onAHinzufuegen(null);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }          
    }//GEN-LAST:event_onAuftragMouseClicked

    private void onZeigeAlleAuftraege1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onZeigeAlleAuftraege1
        auftragModel.setAuftragFilter(new AuftragByTNrFilter(
                            selectedTransport.getTransportNummer()));
    }//GEN-LAST:event_onZeigeAlleAuftraege1

    private void onZeigeAlleAuftraege(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onZeigeAlleAuftraege
        auftragModel.setAuftragFilter(new AlleAuftragFilter());

    }//GEN-LAST:event_onZeigeAlleAuftraege

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransportAuftragsErstellungGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransportAuftragsErstellungGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransportAuftragsErstellungGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransportAuftragsErstellungGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransportAuftragsErstellungGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAHinzufuegen;
    private javax.swing.JButton btLadeAuftraege;
    private javax.swing.JButton btTHinzufuegen;
    private javax.swing.JButton btZeigeAlleAuftraege;
    private javax.swing.JButton btZeigeAuftraegeFueTnr;
    private javax.swing.JComboBox cbRoutenNummer;
    private javax.swing.JComboBox cbTransportNummer;
    private javax.swing.JFormattedTextField ftfDauerBisBeladung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lTransportNummer;
    private javax.swing.JMenuItem miConfig;
    private javax.swing.JTable tAuftraege;
    private javax.swing.JTable tTranporte;
    private javax.swing.JTextField tfAnzahlAuftraege;
    private javax.swing.JTextField tfAuftragsPfad;
    // End of variables declaration//GEN-END:variables
}
