package vk_warehousing.transportAutragsErstellung.config.dlg;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import vk_warehousing.transportAutragsErstellung.config.data.Config;


public class ConfigDialog extends javax.swing.JDialog {

    private boolean okay=false;

    public boolean isOkay() {
        return okay;
    }
    
    public ConfigDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try
        {          
            //init Combox
            cbTransportNummer.setModel(
                    Config.theInstance().
                            getTransportModel());

            cbRoutenNummer.setModel(
                    Config.theInstance().
                            getRoutenModel());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void initComboBox()
    {
        //init ComboBox für TransportNummer
        DefaultComboBoxModel<String> tNrModel = 
                new DefaultComboBoxModel(
                        Config.theInstance().
                                getTransportNummernAsArray()
                    );
        cbTransportNummer.setModel(tNrModel);
        //init ComboBox für RoutenNummer
        DefaultComboBoxModel<String> rNrModel = 
                new DefaultComboBoxModel(
                        Config.theInstance().
                                getRoutenNummernAsArray()
                    );
        cbRoutenNummer.setModel(rNrModel);
            

    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfTransportNummer = new javax.swing.JTextField();
        cbTransportNummer = new javax.swing.JComboBox();
        btTransportNummerHinzufuegen = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbRoutenNummer = new javax.swing.JComboBox();
        btRoutenNummerHinzufuegen = new javax.swing.JButton();
        tfRoutenNummer = new javax.swing.JTextField();
        btRemoveSelectedRoutenNummer = new javax.swing.JButton();
        btRemoveSelectedTransportNummer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btAbbrechen = new javax.swing.JButton();
        btOkay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Config Dialog");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Transport Nr:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(jLabel1, gridBagConstraints);

        tfTransportNummer.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(tfTransportNummer, gridBagConstraints);

        cbTransportNummer.setMinimumSize(new java.awt.Dimension(60, 20));
        cbTransportNummer.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(cbTransportNummer, gridBagConstraints);

        btTransportNummerHinzufuegen.setText("Hinzufügen");
        btTransportNummerHinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAddTransportNummer(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(btTransportNummerHinzufuegen, gridBagConstraints);

        jLabel2.setText("Routen Nr:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(jLabel2, gridBagConstraints);

        cbRoutenNummer.setMinimumSize(new java.awt.Dimension(60, 20));
        cbRoutenNummer.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(cbRoutenNummer, gridBagConstraints);

        btRoutenNummerHinzufuegen.setText("Hinzufügen");
        btRoutenNummerHinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onRoutenNummerHinzufuegen(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(btRoutenNummerHinzufuegen, gridBagConstraints);

        tfRoutenNummer.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(tfRoutenNummer, gridBagConstraints);

        btRemoveSelectedRoutenNummer.setText("Entferne");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(btRemoveSelectedRoutenNummer, gridBagConstraints);

        btRemoveSelectedTransportNummer.setText("Entferne ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(btRemoveSelectedTransportNummer, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 30, 0));

        btAbbrechen.setText("Abbrechen");
        btAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAbbrechen(evt);
            }
        });
        jPanel2.add(btAbbrechen);

        btOkay.setText("Okay");
        btOkay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOkay(evt);
            }
        });
        jPanel2.add(btOkay);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onAddTransportNummer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAddTransportNummer
        try
        {
            Config.theInstance().addTransportNummer(
                            tfTransportNummer.getText());
            //Model für Combobox neu erzeugen mit sortierter Reihenfolge
            cbTransportNummer.setModel(
                    Config.theInstance().
                            getTransportModel());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        
    }//GEN-LAST:event_onAddTransportNummer

    private void onRoutenNummerHinzufuegen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onRoutenNummerHinzufuegen
        try
        {
            Config.theInstance().addRoutenNummer(
                            tfRoutenNummer.getText());
            cbRoutenNummer.addItem(tfRoutenNummer.getText());
            cbRoutenNummer.setModel(
                    Config.theInstance().
                            getRoutenModel());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        
    }//GEN-LAST:event_onRoutenNummerHinzufuegen

    private void onWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onWindowClosing
        try
        {
        //Config.theInstance().save();            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        
          
    }//GEN-LAST:event_onWindowClosing

    private void onAbbrechen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAbbrechen
        okay=false;
        dispose();
    }//GEN-LAST:event_onAbbrechen

    private void onOkay(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOkay
        try
        {
            okay=true;
            Config.theInstance().save();
            dispose();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        
    }//GEN-LAST:event_onOkay
          
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfigDialog dialog = new ConfigDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbbrechen;
    private javax.swing.JButton btOkay;
    private javax.swing.JButton btRemoveSelectedRoutenNummer;
    private javax.swing.JButton btRemoveSelectedTransportNummer;
    private javax.swing.JButton btRoutenNummerHinzufuegen;
    private javax.swing.JButton btTransportNummerHinzufuegen;
    private javax.swing.JComboBox cbRoutenNummer;
    private javax.swing.JComboBox cbTransportNummer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfRoutenNummer;
    private javax.swing.JTextField tfTransportNummer;
    // End of variables declaration//GEN-END:variables
}
